<style>
  .pagemenuon {
padding:0 10px 0 10px ;
color:#000000;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
border-right:dotted 1px #3388cc;
  }
  .pagemenuon a, a:link, a:active, a:hover {
color:#3388cc;
  }
  .pagemenuoff {
padding:0 10px 0 10px ;
color:#888888;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
border-right:dotted 1px #3388cc;
  }
  .pagemenuoff a, a:link, a:active, a:hover {
color:#3388cc;
  }
</style>

  <div style="padding:10px;text-align:left;">
    <a href="/giletter/iletter.asp">
    <span class="pagemenuon">¡÷∞£∑π≈Õ</span>
    </a>
    <a href="/giletter/topicletter.asp">
    <span class="pagemenuon">TOPIC∑π≈Õ</span>
    </a>
  </div>


  <div style="clear:both;"></div>

  