<style>
  .pagemenuon {
padding:0 10px 0 10px ;
color:#000000;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
border-right:dotted 1px #3388cc;
  }
  .pagemenuon a, a:link, a:active, a:hover {
color:#3388cc;
  }
  .pagemenuoff {
padding:0 10px 0 10px ;
color:#888888;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
border-right:dotted 1px #3388cc;
  }
  .pagemenuoff a, a:link, a:active, a:hover {
color:#3388cc;
  }
</style>

  <div style="padding:10px 10px 10px 0;text-align:left;">
    <a href="/bsinfo/proposal.asp">
    <span class="pagemenuon">¿œπ›¡§∫∏</span>
    </a>
    <a href="/bsinfo/">
    <span class="pagemenuon">ºº∞ËTOPIC</span>
    </a>
  </div>


  <div style="clear:both;"></div>

  