</div>
<!-- //content -->
</div>
<!-- //container -->
<script type="text/javascript" language="JavaScript" src="http://www.globalintelligence.kr/_script/connect.js"></script>

<!-- footer -->
<div id="footer">

  <div class="inner">

    <ul>
      <li>
        <a href="/sucustomer/terms.asp">이용약관</a>
      </li>
      <li>
        <a href="#">
          <a href="/sucustomer/private_info.asp"><strong>개인정보수집 및 이용안내</strong></a>
        </a>
      </li>
      <li>
        <a href="/sucustomer/private_policy.asp">개인정보 취급방침</a>
      </li>
    </ul>
    <ul class="member">
      <li>
        <a href="/intro/gameintro.asp">게임소개</a>
      </li>
      <li>
        <a href="/intro/gamemethod.asp">게임방법</a>
      </li>
      <li>
        <a href="/intro/betrule.asp">베팅규칙</a>
      </li>
    </ul>
  </div>
  <div class="inner_v2">

    <div class="footer_logo">
      <a href="#">
        <img src="/img/footer_logo.png" width="119" height="23" alt="" />
      </a>
    </div>

    <div class="inner_add">
      <ul class="sns">
        <li>
            <img src="/img/ico_kakao.png" width="24" height="24" alt="카카오톡 바로가기" />
        </li>
        <li>
            <img src="/img/ico_telegram.png" width="24" height="24" alt="텔레그램 바로가기" />
        </li>
        <li>
            <img src="/img/ico_fb.png" width="24" height="24" alt="페이스북 바로가기" OnClick="javascript:SendFaceBook( 'hhs1052를 친추해주세요', '항하사' ); " style="cursor:pointer;" >
            </li>
        <li>
            <img src="/img/ico_twit.png" width="25" height="24" alt="트위터 바로가기" OnClick="javascript:SendTwitter( 'hhs1052를 친추해주세요', '항하사' ); " style="cursor:pointer;" >
        </li>
      </ul>
      <p class="add">3156 Shadowridge Ave Las Vegas, NV 89120 United staes of America</p>
      <p class="copy">
        Copyright &copy; <span>1052 HANGHASA</span>. All Rights Reserved.
      </p>
    </div>


    <span class="qrcode">
      <img src="/img/qrcode.gif" width="70" height="70" alt="항하사증권 QR코드" />
    </span>
  </div>

</div>
<!-- //footer -->


</div>
</div>
</body>
</html>

