<style>
  .pagemenuon {
padding:0 10px 0 10px ;
color:#000000;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
border-right:dotted 1px #cc3388;
  }
  .pagemenuon a, a:link, a:active, a:hover {
color:#3388cc;
  }
  .pagemenuoff {
padding:0 10px 0 10px ;
color:#3388cc;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
border-right:dotted 1px #3388cc;
  }
  .pagemenuoff a, a:link, a:active, a:hover {
color:#3388cc;
  }
  .jumplink {
padding:0 10px 0 10px ;
color:#FF6600;
font-family:∏º¿∫ ∞ÌµÒ,Arial;
font-size:12pt;
font-weight:bold;
  }
</style>

  <div id="guideleft">
  ¢√ √•¿–æÓ¡÷±‚ - <%=menu_desc %>
  </div>
  <div id="guide">
  <a href="/">HOME</a> >
  <a href="/btshop/">√•¿–æÓ¡÷±‚</a> >
  <span class="sel"><%=menu_desc %></span>
  </div>

  <div style="clear:both;"></div>

  