<style>
        .creativebox
        {
            background-color:#ffffff;
            width:270px;
            float:none;
            position:relative;
        }
        .creativebox .title 
        {
            background-color:#ffffff;
            text-align:center;
            color:#3388cc;
            font-size:9pt;
            font-weight:bold;
            padding:7px 0 7px 0;
            border-bottom:dotted 1px #dddddd;
        }
        .creativebox .title span
        {
            width:60;
            margin:0px 5px 0px 5px;
        }
        .creativebox .sublist 
        {
            background-color:#ffffff;
            text-align:left;
            padding:5px 0 5px 8px;
            border-bottom:dotted 1px #dddddd;
        }
        .creativebox .sublist a
        {
            color:#000000;
            font-size:8pt;
        }
        .creativebox .sublist a:hover
        {
            color:#888888;
            font-size:8pt;
        }
</style>
<div class="creativebox">
  <div class="title">
  <img src="/images/logo_computerworld.png" style="height:14px;border:0px;" >
  디지털문명 초연결사회, 창조경제논의
  </div>
  <div class="sublist">
  <a href="http://www.itdaily.kr/atl/view.asp?a_id=45000">1. Prologue</a>
  </div>
  <div class="sublist">
  <a href="http://www.itdaily.kr/atl/view.asp?a_id=45908">2. 초연결사회, 지배·영리·수혜의 역할분담</a>
  </div>
  <div class="sublist">
  <a href="http://www.itdaily.kr/atl/view.asp?a_id=46869">3. 융합과연결의MATRIX화, 창의산업과 서비스</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=47730">4. 국가는 P2P협치, 사회는 글로벌디지털공동체화</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=47765">5. 세계구조 - 자유무역,왕래 하나의 디지털 세상</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=47830">6. 인간의 삶 - 디지털 신인류, 온오프라인 융합 공동체의 형성</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=47841">7. 창조경제의 디지털문화 ? “세계의 하나로” 숙제와 “창조적(Creative)”의 위험</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=47874">8.과학기술융합 ? 디지털전환의 4가지 변화</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=47904">9.실세상의 변화 - 디지털 초연결 “글로벌 권력과 부의 재편”</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=48047">10.디지털 기준 - 인류는 “디지털 기준(Digital Normal)”으로 새로운 문명을 세워가야 한다.</a>
  </div>
  <div class="sublist">
  <a href="http://www.comworld.co.kr/news/articleView.html?idxno=48245">11.디지털문명 ? A2B와 B2A의 상호작용 ‘하나의 세계, 디지털 문명화‘</a>
  </div>
</div>


’