<!-- #include virtual="/_include/top_common.inc" -->
<link rel="stylesheet" href="/_css/body_prosuming.css">

<% menu_main = "project" %>
<!-- #include virtual="/_include/top_menu_main.inc" -->

<div id="submenu2"> 
  <div class="blank"></div>
  <ul> 
    <li><a href="/bsinfo/proposal.asp">일반정보</a></li>
    <li><a href="/bsinfo/">세계TOPIC</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <a href="/gimember/subscribe.asp"><img src="/images/subscribe_btn.png" style="border:solid 0px #ffffff;height:20px;width:70px" id="mysubscribe"></a>
  </ul>
</div>
<div style="clear:both;border-bottom:solid 1px #dddddd;"></div>
