<!-- #include virtual="/_include/check_work.inc" -->
<!-- #include virtual="/_include/top_common.inc" -->

<!-- #include virtual="/_include/top_menu_main.inc" -->

<div id="submenu2"> 
  <div class="blank"></div>
  <ul> 
    <li><a href="/bswork/book/">책코드등록</a></li>
    <li><a href="/bswork/">책요약작업</a></li>
    <li><a href="/help/bookwork.asp">작업방법</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <a href="/gimember/subscribe.asp"><img src="/images/subscribe_btn.png" style="border:solid 0px #ffffff;height:20px;width:70px" id="mysubscribe"></a>
  </ul>
</div>

<div style="clear:both;border-bottom:solid 1px #dddddd;"></div>

