<!-- #include virtual="/_include/top_common.inc" -->
<link rel="stylesheet" href="/_css/body_home.css">

<% menu_main = "intro" %>
<!-- #include virtual="/_include/top_menu_main.inc" -->

<div id="submenu2"> 
  <div class="blank"></div>
  <ul> 
    <li><a href="/bsbooks/">책요약</a></li>
    <li><a href="/bsbooks/booklist.asp">책코드</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <a href="#"><img src="/images/subscribe_btn.png" style="border:solid 0px #ffffff;height:20px;width:70px" id="mysubscribe"></a>
  </ul>
</div>
<div style="clear:both;border-bottom:solid 1px #dddddd;"></div>
