<!-- #include virtual="/_include/top_common.inc" -->
<link rel="stylesheet" href="/_css/body_home.css">

<% menu_main = "intro" %>
<!-- #include virtual="/_include/top_menu_main.inc" -->

<div id="submenu2"> 
  <div class="blank"></div>
  <ul> 
    <li><a href="/bsapp/">샵 앱</a></li>
    <li><a href="/bsapp/app_design.asp">앱 디자인</a></li>
    <li><a href="/gimember/app_request.asp">앱 신청</a></li>
    <li><a href="/bsshop/intro.asp">소개</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <a href="#"><img src="/images/subscribe_btn.png" style="border:solid 0px #ffffff;height:20px;width:70px" id="mysubscribe"></a>
  </ul>
</div>
<div style="clear:both;border-bottom:solid 1px #dddddd;"></div>
