<div id="topmenuwhite"> 
  <div class="blank"></div>
  <ul> 
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="/intro/gameintro.asp">게임소개</a></li>
  <% else %>
    <li class="light2"><a href="/intro/gameintro.asp">게임소개</a></li>
  <% end if %>
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="/suupdown/kospi.asp">UP & DOWN</a></li>
  <% else %>
    <li class="light2"><a href="/suupdown/kospi.asp">UP & DOWN</a></li>
  <% end if %>
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="/suitem/">종목매치</a></li>
  <% else %>
    <li class="light2"><a href="/suitem/">종목매치</a></li>
  <% end if %>
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="/sutheme/">종목레이스</a></li>
  <% else %>
    <li class="light2"><a href="/sutheme/">종목레이스</a></li>
  <% end if %>
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="/suresult/">게임결과</a></li>
  <% else %>
    <li class="light2"><a href="/suresult/">게임결과</a></li>
  <% end if %>
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="#">증권정보</a></li>
  <% else %>
    <li class="light2"><a href="#">증권정보</a></li>
  <% end if %>
  <% if menu_main = "shop" then %>
    <li class="sel2"><a href="/sucustomer/terms.asp">고객센터</a></li>
  <% else %>
    <li class="light2"><a href="/sucustomer/terms.asp">고객센터</a></li>
  <% end if %>
  </ul>
</div>
<div style="clear:both;"></div>

